### ISSUE TITLE
Feature Request - Hide Game Bar when talking head / npc dialogue is open.

### ISSUE THREAD

**Issue by Fizgig1973** [wind-addons/ElvUI_WindTools#431]
Would love to have an option to have the Game Bar hide when speaking to NPCs.

**Comment by fang2hou** [comment]
You can try this addon to hide game ui when talking to NPCs
https://www.curseforge.com/wow/addons/dialogueui

**Comment by Fizgig1973** [comment]
Thanks, but I use Immersion. Hence the request lol.

**Comment by fang2hou** [comment]
WindTools provides a gaming bar, and you want to hide when Immersion appears. But the hiding should not be provided by WindTools, because not everyone is using Immersion. This feature should be provided by hiding UI plugins or immersion rather than WindTools.

After the release of Dialogue UI, in fact, many Immersion users have begun to turn to Dialogue UI. And Immersion now causes many problems like sometimes cannot turn in the quest, the Immersion skin is also planned to be removed in future version.

**Comment by Fizgig1973** [comment]
I totally understand. I really  like Dialogue UI, I just wished it skinned like ElvUi so it would match the rest. 

Thank you for all your work, it is really appreciated.
